### ISSUE TITLE
Error during startup (no internet)

### ISSUE THREAD

**Issue by omaishar** [sidneys/pushbullet-desktop#128]
MacOS Catalina 10.15.6 (19G2021)
PB for Desktop 11.0.2

<img width="378" alt="image" src="https://user-images.githubusercontent.com/14070203/92592742-bc8ce800-f2a8-11ea-8fd1-48775647f6da.png">

**Comment by omaishar** [comment]
It was due to a disconnected network (no internet).
I would suggest a better error message.

**Comment by sidneys** [comment]
@omaishar Thank you!
