### ISSUE TITLE
stops after suspending

### ISSUE THREAD

**Issue by jbytes1027** [sidneys/pushbullet-desktop#133]
## 🤷🏽‍♂️ Current Behaviour

notifications (and maybe other functionality) stop working after waking up from suspend

## 🏡 Environmental Context

**App Version**
11.0.2-491
**Installation Type** 
deb
**Operating System**
pop os 20.04

**Comment by danlo315** [comment]
Reporting the same issue.  Restarting PB for desktop restores functionality.

**Comment by jbytes1027** [comment]
No longer invested
